version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    env_file:
      - ./.env
      - ./.mongo.env
    container_name: task-backend
  mongo:
    image: mongo
    env_file:
      - ./.mongo.env
    volumes:
      - task-db:/data/db
    container_name: task-db
volumes:
  task-db:
